run:
  timeout: 5m
  go: "1.24"
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: gswarm-sidecar
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - funlen
        - gocyclo
        - dupl
        - gosec
    - path: internal/processor/
      linters:
        - gocyclo
        - funlen
    - linters:
        - gosec
      text: "G101"
      path: internal/blockchain/
    - linters:
        - gosec
      text: "G204"
      path: internal/blockchain/
    - linters:
        - gosec
      text: "G307"
      path: internal/blockchain/
    - linters:
        - gosec
      text: "G401"
      path: internal/blockchain/
    - linters:
        - gosec
      text: "G501"
      path: internal/blockchain/
    - linters:
        - gosec
      text: "G601"
      path: internal/blockchain/
  max-issues-per-linter: 0
  max-same-issues: 0 