node_id: "my-node-123" # Change this to whatever you want your node name to
jwt_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."  # <-- Replace with your actual JWT from the gswarm.dev dashboard (https://gswarm.dev/dashboard) authenticate with ethereum wallet wallet.

# logs:
#   swarm_log_path: "./logs/swarm.log"
#   yarn_log_path: "./logs/yarn.log"
#   wandb_log_path: "./logs/wandb/"

log_monitoring:
  api_endpoint: "https://h9oy4hruxf.execute-api.us-east-1.amazonaws.com/prod/v1/ingest" # Leave this unless you have your own custom backend.
  batch_size: 10
  batch_flush_interval: 10
  initial_tail_lines: 100
  log_files:
    - "./logs/swarm_launcher.log"  # Main RL-Swarm log file could be in a couple locations depending on if you are using docker or not.
    # - "./logs/yarn.log" # Only uncomment these if you know what you are doing
    # - "./logs/wandb/debug.log"  # Uncomment to enable

telegram:
  bot_token:    "6139877560:AAE..."      # <-- your token
  chat_id:      "-1001876543210"         # <-- DM or channel id
  alert_on_down: true                    # <-- turn pings on
  down_alert_delay: 300                  # <-- seconds to wait before alerting (example: 5 minutes)
