node_id: "my-node-123" # Change this to whatever you want your node name to
jwt_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."  # <-- Replace with your actual JWT from the gswarm.dev dashboard (https://gswarm.dev/dashboard) authenticate with ethereum wallet wallet.

# logs:
#   swarm_log_path: "./logs/swarm.log"
#   yarn_log_path: "./logs/yarn.log"
#   wandb_log_path: "./logs/wandb/"

system:
  poll_interval: 10
  enable_gpu: true
  enable_cpu: true
  enable_ram: true
  batch_size: 10

log_monitoring:
  api_endpoint: "https://h9oy4hruxf.execute-api.us-east-1.amazonaws.com/prod/v1/ingest" # Leave this unless you have your own custom backend.
  batch_size: 10
  batch_flush_interval: 10
  initial_tail_lines: 100
  log_files:
    - "./logs/swarm_launcher.log"  # Main RL-Swarm log file could be in a couple locations depending on if you are using docker or not.
    # - "./logs/yarn.log" # Only uncomment these if you know what you are doing
    # - "./logs/wandb/debug.log"  # Uncomment to enable

api:
  base_url: "https://gswarm.dev"
  metrics_endpoint: "/api/v1/metrics"
  health_endpoint: "/api/v1/health"
  auth_token: "YOUR_JWT_TOKEN_HERE"
  timeout: 10
  retry_count: 3
  blockchain_latest_endpoint: "/api/v1/latest-blockchain"

blockchain:
  contract_address: "0xFaD7C5e93f28257429569B854151A1B8DCD404c2"
  rpc_url: "https://gensyn-testnet.g.alchemy.com/public"
  chain_id: 1234
  contract_abi_path: "./configs/contract.abi.json"
  poll_interval: 300
  send_interval: 300
  node_eoa: "0xYourNodeEOA" # <---Change this to your node EOA address
  node_peer_id: "your-unique-peer-id"

telegram:
  bot_token:    "6139877560:AAE..."      # <-- your token
  chat_id:      "-1001876543210"         # <-- DM or channel id
  alert_on_down: true                    # <-- turn pings on
  down_alert_delay: 900                  # <-- seconds to wait before alerting (15 minutes)
