node_id: "my-node-123"
jwt_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."  # <-- Replace with your actual JWT

logs:
  swarm_log_path: "./logs/swarm.log"
  yarn_log_path: "./logs/yarn.log"
  wandb_log_path: "./logs/wandb/"

log_monitoring:
  api_endpoint: "https://h9oy4hruxf.execute-api.us-east-1.amazonaws.com/prod/v1/ingest"
  batch_size: 10
  batch_flush_interval: 10
  initial_tail_lines: 100
  log_files:
    - "./logs/swarm.log"
    - "./logs/yarn.log"
    # - "./logs/wandb/debug.log"  # Uncomment to enable
